// Generated by scripts/city04_generate.py from the accepted CITY-03 projection.
// Do not edit by hand. The Markdown seed remains authoritative.
using UnityEngine;
namespace Arkus.CITY {
public static class City04Layout {
public const string SourceBlob = "3186b80d173cd20f961f33d5a28bf447b2c6971d";
public struct Region { public string Id, Role; public Vector2[] Points; public Region(string id, string role, Vector2[] points) { Id=id; Role=role; Points=points; } }
public struct Route { public string Id; public float Width; public Vector2[] Points; public Route(string id, float width, Vector2[] points) { Id=id; Width=width; Points=points; } }
public static readonly Vector2[] OUTER = new[] { new Vector2(-20.000000f, -60.000000f), new Vector2(70.000000f, -80.000000f), new Vector2(205.000000f, -48.000000f), new Vector2(245.000000f, 22.000000f), new Vector2(220.000000f, 95.000000f), new Vector2(150.000000f, 145.000000f), new Vector2(70.000000f, 132.000000f), new Vector2(-20.000000f, 55.000000f) };
public static readonly Vector2[] RIO = new[] { new Vector2(-20.000000f, -8.000000f), new Vector2(0.000000f, -10.000000f), new Vector2(20.000000f, -24.000000f), new Vector2(40.000000f, -42.000000f), new Vector2(60.000000f, -46.000000f), new Vector2(95.000000f, -45.000000f), new Vector2(140.000000f, -42.000000f), new Vector2(185.000000f, -40.000000f), new Vector2(205.000000f, -38.000000f), new Vector2(205.000000f, -48.000000f), new Vector2(185.000000f, -52.000000f), new Vector2(140.000000f, -57.000000f), new Vector2(95.000000f, -61.000000f), new Vector2(60.000000f, -62.000000f), new Vector2(40.000000f, -58.000000f), new Vector2(20.000000f, -43.000000f), new Vector2(0.000000f, -30.000000f), new Vector2(-20.000000f, -24.000000f) };
public static readonly Vector2[] ARROYO = new[] { new Vector2(-20.000000f, -8.000000f), new Vector2(0.000000f, 10.000000f), new Vector2(20.000000f, 28.000000f), new Vector2(40.000000f, 48.000000f), new Vector2(60.000000f, 68.000000f), new Vector2(78.000000f, 90.000000f), new Vector2(88.000000f, 111.000000f), new Vector2(108.000000f, 132.000000f), new Vector2(120.000000f, 140.125000f), new Vector2(100.000000f, 136.875000f), new Vector2(99.000000f, 130.000000f), new Vector2(90.000000f, 118.000000f), new Vector2(82.000000f, 106.000000f), new Vector2(70.000000f, 86.000000f), new Vector2(50.000000f, 60.000000f), new Vector2(30.000000f, 40.000000f), new Vector2(8.000000f, 20.000000f), new Vector2(-20.000000f, 4.000000f) };
public static readonly Vector2[] X1 = new[] { new Vector2(53.000000f, -33.000000f), new Vector2(45.000000f, -65.000000f), new Vector2(39.000000f, -63.000000f), new Vector2(47.000000f, -31.000000f) };
public static readonly Vector2[] X5 = new[] { new Vector2(90.500000f, 107.800000f), new Vector2(88.500000f, 121.800000f), new Vector2(91.500000f, 122.200000f), new Vector2(93.500000f, 108.200000f) };
public static readonly Region[] STUBS = new[] {
new Region("stub.x1.wedge", "receiving stub", new[] { new Vector2(42.000000f, -40.000000f), new Vector2(58.000000f, -40.000000f), new Vector2(58.000000f, -22.000000f), new Vector2(42.000000f, -22.000000f) }),
new Region("stub.x1.orilla", "receiving stub", new[] { new Vector2(34.000000f, -69.000000f), new Vector2(50.000000f, -72.000000f), new Vector2(52.000000f, -62.000000f), new Vector2(37.000000f, -60.000000f) }),
new Region("stub.x5.wedge", "receiving stub", new[] { new Vector2(84.000000f, 99.000000f), new Vector2(99.000000f, 99.000000f), new Vector2(96.000000f, 108.000000f), new Vector2(87.000000f, 108.000000f) }),
new Region("stub.x5.ensanche", "receiving stub", new[] { new Vector2(86.000000f, 119.000000f), new Vector2(93.000000f, 124.000000f), new Vector2(94.000000f, 130.000000f), new Vector2(84.000000f, 128.000000f) })
};
public static readonly Region[] SITES = new[] {
new Region("F01", "bar I3", new[] { new Vector2(88.000000f, 45.000000f), new Vector2(96.000000f, 45.000000f), new Vector2(96.000000f, 60.000000f), new Vector2(88.000000f, 60.000000f) }),
new Region("F02", "civic I2", new[] { new Vector2(148.000000f, 66.000000f), new Vector2(166.000000f, 66.000000f), new Vector2(166.000000f, 88.000000f), new Vector2(148.000000f, 88.000000f) }),
new Region("F03", "shop I1", new[] { new Vector2(188.000000f, 76.000000f), new Vector2(198.000000f, 76.000000f), new Vector2(198.000000f, 94.000000f), new Vector2(188.000000f, 94.000000f) }),
new Region("F04", "closed I0", new[] { new Vector2(62.000000f, 40.000000f), new Vector2(69.000000f, 40.000000f), new Vector2(69.000000f, 54.000000f), new Vector2(62.000000f, 54.000000f) }),
new Region("F05", "closed I0", new[] { new Vector2(98.000000f, 24.000000f), new Vector2(105.000000f, 24.000000f), new Vector2(105.000000f, 36.000000f), new Vector2(98.000000f, 36.000000f) }),
new Region("F06", "closed I0", new[] { new Vector2(126.000000f, 62.000000f), new Vector2(138.000000f, 62.000000f), new Vector2(138.000000f, 78.000000f), new Vector2(126.000000f, 78.000000f) }),
new Region("F07", "closed I0", new[] { new Vector2(170.000000f, 74.000000f), new Vector2(178.000000f, 74.000000f), new Vector2(178.000000f, 90.000000f), new Vector2(170.000000f, 90.000000f) }),
new Region("F08", "closed I0", new[] { new Vector2(50.000000f, 3.000000f), new Vector2(57.000000f, 3.000000f), new Vector2(57.000000f, 16.000000f), new Vector2(50.000000f, 16.000000f) }),
new Region("S01", "market apron", new[] { new Vector2(132.000000f, 35.000000f), new Vector2(150.000000f, 40.000000f), new Vector2(148.000000f, 52.000000f), new Vector2(130.000000f, 47.000000f) }),
new Region("S02", "X1 bridgehead", new[] { new Vector2(42.000000f, -40.000000f), new Vector2(58.000000f, -40.000000f), new Vector2(58.000000f, -22.000000f), new Vector2(42.000000f, -22.000000f) }),
new Region("S03", "semi-private court", new[] { new Vector2(70.000000f, 55.000000f), new Vector2(83.000000f, 55.000000f), new Vector2(83.000000f, 68.000000f), new Vector2(70.000000f, 68.000000f) })
};
public static readonly Region[] ANCHORS = new[] {
new Region("W.LANDING", "anchor", new[] { new Vector2(0.000000f, 0.000000f) }),
new Region("W.X1", "anchor", new[] { new Vector2(50.000000f, -32.000000f) }),
new Region("O.X1", "anchor", new[] { new Vector2(42.000000f, -64.000000f) }),
new Region("W.CASCO", "anchor", new[] { new Vector2(80.000000f, 35.000000f) }),
new Region("W.X5", "anchor", new[] { new Vector2(92.000000f, 108.000000f) }),
new Region("E.X5", "anchor", new[] { new Vector2(90.000000f, 122.000000f) }),
new Region("W.PLAZA", "anchor", new[] { new Vector2(150.000000f, 58.000000f) }),
new Region("W.SHOP", "anchor", new[] { new Vector2(195.000000f, 70.000000f) })
};
public static readonly Route[] ROUTES = new[] {
new Route("W04", 5.000000f, new[] { new Vector2(195.000000f, 70.000000f), new Vector2(181.000000f, 63.000000f), new Vector2(165.000000f, 58.000000f), new Vector2(150.000000f, 58.000000f) }),
new Route("W05", 3.000000f, new[] { new Vector2(150.000000f, 58.000000f), new Vector2(126.000000f, 51.000000f), new Vector2(104.000000f, 40.000000f), new Vector2(80.000000f, 35.000000f) }),
new Route("W06", 2.800000f, new[] { new Vector2(80.000000f, 35.000000f), new Vector2(63.000000f, 23.000000f), new Vector2(51.000000f, 10.000000f), new Vector2(31.000000f, 15.000000f), new Vector2(16.000000f, 5.000000f), new Vector2(0.000000f, 0.000000f) }),
new Route("W12", 2.800000f, new[] { new Vector2(80.000000f, 35.000000f), new Vector2(68.000000f, 18.000000f), new Vector2(56.000000f, 0.000000f), new Vector2(50.000000f, -32.000000f) }),
new Route("W13", 2.600000f, new[] { new Vector2(80.000000f, 35.000000f), new Vector2(69.000000f, 50.000000f), new Vector2(70.000000f, 72.000000f), new Vector2(82.000000f, 90.000000f), new Vector2(92.000000f, 108.000000f) }),
new Route("casco.micro.A", 2.400000f, new[] { new Vector2(73.000000f, 30.000000f), new Vector2(78.000000f, 36.000000f), new Vector2(86.000000f, 38.000000f), new Vector2(91.000000f, 34.000000f) }),
new Route("casco.micro.B", 2.400000f, new[] { new Vector2(73.000000f, 30.000000f), new Vector2(78.000000f, 25.000000f), new Vector2(86.000000f, 27.000000f), new Vector2(91.000000f, 34.000000f) }),
new Route("X1", 5.500000f, new[] { new Vector2(50.000000f, -32.000000f), new Vector2(42.000000f, -64.000000f) }),
new Route("X5", 2.500000f, new[] { new Vector2(92.000000f, 108.000000f), new Vector2(90.000000f, 122.000000f) })
};
}
}
