<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Arkus.DesignWorld</AssemblyName>
    <RootNamespace>Arkus.DesignWorld</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Arkus.Game.World/Arkus.Game.World.csproj" />
  </ItemGroup>
</Project>
