<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Arkus.Game.Authoring/Arkus.Game.Authoring.csproj" />
    <ProjectReference Include="../Arkus.Game.Validation/Arkus.Game.Validation.csproj" />
    <ProjectReference Include="../Arkus.Harness.Protocol/Arkus.Harness.Protocol.csproj" />
  </ItemGroup>

</Project>
