<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Arkus.Game.Authoring</AssemblyName>
    <RootNamespace>Arkus.Game.Authoring</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Arkus.Game.Core/Arkus.Game.Core.csproj" />
    <ProjectReference Include="../Arkus.Game.Validation/Arkus.Game.Validation.csproj" />
    <ProjectReference Include="../Arkus.Game.World/Arkus.Game.World.csproj" />
    <ProjectReference Include="../Arkus.Harness.Protocol/Arkus.Harness.Protocol.csproj" />
  </ItemGroup>
</Project>
