"""Rebuild CITY-04 Unity greybox projections from the accepted CITY-03 seed.

Requires shapely==2.1.2 (GEOS 3.13). Run from the repository root. The source
blob guard deliberately fails if CITY-03 is amended without re-authoring this
bounded projection. Generated meshes/C# are inspectable outputs, not CITY truth.
"""

from __future__ import annotations

import hashlib
import json
import math
import subprocess
from pathlib import Path

from shapely import Polygon, box, constrained_delaunay_triangles, unary_union


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "Unity/ArkusUnity/Assets/Arkus/CITY"
LAYOUT = ASSETS / "City04Layout.json"
MESHES = ASSETS / "Meshes"


def poly(points):
    result = Polygon(points)
    if not result.is_valid or result.is_empty:
        raise ValueError("invalid CITY-03 projected polygon")
    return result


def regions(geom):
    if geom.is_empty:
        return
    if geom.geom_type == "Polygon":
        yield geom
    elif hasattr(geom, "geoms"):
        for part in geom.geoms:
            yield from regions(part)


def height(u, v):
    # Temporary physical grade hypothesis. CITY-04 must measure and falsify it.
    casco = 3.0 * math.exp(-((u - 80) ** 2 + (v - 35) ** 2) / 2500)
    plaza = 2.0 * math.exp(-((u - 150) ** 2 + (v - 58) ** 2) / 3500)
    return 0.015 * u + 0.025 * v + casco + plaza


def triangles(geom, pitch=8):
    min_u, min_v, max_u, max_v = geom.bounds
    for u in range(math.floor(min_u / pitch) * pitch, math.ceil(max_u / pitch) * pitch, pitch):
        for v in range(math.floor(min_v / pitch) * pitch, math.ceil(max_v / pitch) * pitch, pitch):
            clipped = geom.intersection(box(u, v, u + pitch, v + pitch))
            for piece in regions(clipped):
                for tri in constrained_delaunay_triangles(piece).geoms:
                    if tri.area > 1e-8:
                        yield list(tri.exterior.coords)[:3]


def write_obj(name, geom, elevation):
    lines = [f"# CITY-04 generated projection: {name}"]
    count = 0
    for tri in triangles(geom):
        for u, v in tri:
            # This Unity OBJ importer reverses OBJ X while keeping OBJ Z.
            # Supply (-U,V) so the imported world coordinates are (U,V).
            lines.append(f"v {-u:.6f} {elevation(u, v):.6f} {v:.6f}")
        # This is a 180-degree rotation from the prior mesh and preserves winding.
        ax, ay = tri[0]
        bx, by = tri[1]
        cx, cy = tri[2]
        face = (3, 2, 1) if (bx - ax) * (cy - ay) - (by - ay) * (cx - ax) < 0 else (1, 2, 3)
        lines.append("f " + " ".join(str(count + i) for i in face))
        count += 3
    path = MESHES / (name + ".obj")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")
    return count // 3


def vec(point):
    return f"new Vector2({point[0]:.6f}f, {point[1]:.6f}f)"


def array(points):
    return "new[] { " + ", ".join(map(vec, points)) + " }"


def cs_string(value):
    return json.dumps(value, ensure_ascii=True)


def write_csharp(layout):
    lines = [
        "// Generated by scripts/city04_generate.py from the accepted CITY-03 projection.",
        "// Do not edit by hand. The Markdown seed remains authoritative.",
        "using UnityEngine;",
        "namespace Arkus.CITY {",
        "public static class City04Layout {",
        f"public const string SourceBlob = {cs_string(layout['source_blob'])};",
        "public struct Region { public string Id, Role; public Vector2[] Points; public Region(string id, string role, Vector2[] points) { Id=id; Role=role; Points=points; } }",
        "public struct Route { public string Id; public float Width; public Vector2[] Points; public Route(string id, float width, Vector2[] points) { Id=id; Width=width; Points=points; } }",
    ]
    for key in ("outer", "rio", "arroyo", "x1", "x5"):
        lines.append(f"public static readonly Vector2[] {key.upper()} = {array(layout[key])};")
    for key in ("stubs", "sites"):
        entries = ",\n".join(
            f"new Region({cs_string(row['id'])}, {cs_string(row.get('role', 'receiving stub'))}, {array(row['points'])})"
            for row in layout[key]
        )
        lines.append(f"public static readonly Region[] {key.upper()} = new[] {{\n{entries}\n}};")
    entries = ",\n".join(
        f"new Region({cs_string(row['id'])}, {cs_string('anchor')}, {array([row['point']])})"
        for row in layout["anchors"]
    )
    lines.append(f"public static readonly Region[] ANCHORS = new[] {{\n{entries}\n}};")
    entries = ",\n".join(
        f"new Route({cs_string(row['id'])}, {row['width']:.6f}f, {array(row['points'])})"
        for row in layout["routes"]
    )
    lines.append(f"public static readonly Route[] ROUTES = new[] {{\n{entries}\n}};")
    lines.append("}")
    lines.append("}")
    (ASSETS / "City04Layout.generated.cs").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    layout = json.loads(LAYOUT.read_text(encoding="utf-8"))
    actual = subprocess.check_output(["git", "hash-object", layout["source"]], cwd=ROOT, text=True).strip()
    if actual != layout["source_blob"]:
        raise SystemExit(f"CITY-03 source blob mismatch: {actual}")
    outer, rio, arroyo = (poly(layout[key]) for key in ("outer", "rio", "arroyo"))
    x1, x5 = (poly(layout[key]) for key in ("x1", "x5"))
    dry = outer.difference(unary_union([rio, arroyo]))
    if not math.isclose(outer.area, 44817.5, abs_tol=1e-6):
        raise SystemExit("outer area does not match accepted CITY-03 geometry")
    if not math.isclose(rio.area, 3505.0, abs_tol=1e-6) or not math.isclose(arroyo.area, 713.6875, abs_tol=1e-6):
        raise SystemExit("water area does not match accepted CITY-03 geometry")
    if len(list(regions(dry))) != 3:
        raise SystemExit("dry land must have exactly three components")
    for site in layout["sites"] + layout["stubs"]:
        if not dry.covers(poly(site["points"])):
            raise SystemExit(f"{site['id']} escapes dry land")
    rio_bank = rio.buffer(3.0).intersection(outer).difference(rio).difference(
        unary_union([x1, poly(layout["stubs"][0]["points"]), poly(layout["stubs"][1]["points"])])
    )
    arroyo_bank = arroyo.buffer(2.0).intersection(outer).difference(arroyo).difference(
        unary_union([x5, poly(layout["stubs"][2]["points"]), poly(layout["stubs"][3]["points"])])
    )
    for site in layout["sites"]:
        if poly(site["points"]).intersection(unary_union([rio_bank, arroyo_bank])).area > 1e-5:
            raise SystemExit(f"{site['id']} enters effective no-build bank")
    route_shapes = [
        __import__("shapely").LineString(route["points"]).buffer(route["width"] / 2, cap_style="flat", join_style="bevel")
        for route in layout["routes"] if route["id"] not in ("X1", "X5")
    ]
    # Bank ground is visual only except accepted routes/stubs. Water remains void.
    walkable = dry.difference(unary_union([rio_bank, arroyo_bank])).union(
        unary_union(route_shapes + [poly(s["points"]) for s in layout["stubs"]]).intersection(dry)
    )
    MESHES.mkdir(parents=True, exist_ok=True)
    counts = {
        "land_visual": write_obj("land_visual", dry, height),
        "walkable_collision": write_obj("walkable_collision", walkable, height),
        "rio_water": write_obj("rio_water", rio, lambda u, v: -1 + 0.006 * u),
        "arroyo_water": write_obj("arroyo_water", arroyo, lambda u, v: -0.5 + 0.006 * u),
        "x1_crossing": write_obj("x1_crossing", x1, lambda u, v: height(u, v) + 0.15),
        "x5_crossing": write_obj("x5_crossing", x5, lambda u, v: height(u, v) + 0.15),
    }
    write_csharp(layout)
    print(json.dumps({"source_blob": actual, "outer_area_m2": outer.area, "dry_components": [round(p.area, 4) for p in regions(dry)], "triangles": counts}, indent=2))


if __name__ == "__main__":
    main()
