<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>Arkus.Kernel.Proof.Tool</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Arkus.Kernel.Proof/Arkus.Kernel.Proof.csproj" />
  </ItemGroup>

</Project>
